apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-uasb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-uasb
    app.kubernetes.io/part-of: test-app-ftlj
  name: test-component-uasb
  namespace: build-e2e-tywr-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: test-component-uasb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: test-component-uasb
    spec:
      containers:
      - image: quay.io/susdas/test-images@sha256:d1bbefcbf97cdffa43d82687056f5eea4c192cee5af5fd5c28508cdb3d07ab8c
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
